### ISSUE TITLE
Request for xv

### ISSUE THREAD

**Issue by lasuit** [joyent/pkgbuild#21]
Even though it's old, and not "free software", could you build xv for the set.  I tried to build it from source, but now it says it's "not signed."

**Comment by jperkin** [comment]
Sorry, no.  Even though it's old the restrictions it places on redistribution still apply.

You should be able to install the package you built yourself by using `pkg_add -C /dev/null /path/to/pkg.tgz`, or by changing the `VERIFIED_INSTALLATION` setting in pkg_install.conf.
