### ISSUE TITLE
php, apache, nginx, build options

### ISSUE THREAD

**Issue by kelewind** [joyent/pkgbuild#3]
Good evening, 

1) if it's possible, build nginx 1.8 package in 2015Q2 branch with headers-more module
http://wiki.nginx.org/HttpHeadersMoreModule#Installation
2) In apache 2.4 apperead new mpm (event). For normal work php with him, that would require a basic package, extensions, and mod_php55 been build supporting ZTS. Its it Possible? Without it, it just does not work

Thanks in advance

**Comment by kelewind** [comment]
regarding the second question - meaning php55

**Comment by jperkin** [comment]
The `headers-more` option will be enabled in the 2015Q3 package set.

As for Apache+PHP, you will need to use the prefork MPM as threaded PHP is not supported.

**Comment by kelewind** [comment]
"As for Apache+PHP, you will need to use the prefork MPM as threaded PHP is not supported"

Tell me, please, planned to support in the future? Since this MPM showed quite good results in the production hight load servers on BSD systems + on SmartOS with Python apps

**Comment by jperkin** [comment]
You'd need to ask the PHP developers.

**Comment by kelewind** [comment]
[root@dev1 /usr/ports/lang/php55]# make showconfig
===> The following configuration options are available for php55-5.5.27:
     CLI=on: Build CLI version
     CGI=on: Build CGI version
     FPM=off: Build FPM version
     EMBED=off: Build embedded library
     DEBUG=off: Enable debug
     DTRACE=off: Enable DTrace support
     IPV6=on: Enable ipv6 support
     MAILHEAD=off: Enable mail header patch
     LINKTHR=on: Link thread lib (for threaded extensions)
     ZTS=on: Force Zend Thread Safety (ZTS) build
===> Use 'make config' to modify these settings

Php version in the ports FreeBSD already supports it

[root@dev1 /usr/ports/www/mod_php55]# make showconfig
===> The following configuration options are available for mod_php55-5.5.27:
     AP2FILTER=off: Use Apache 2.x filter interface (experimental)
     DEBUG=off: Enable debug
     DTRACE=off: Enable DTrace support
     IPV6=on: Enable ipv6 support
     MAILHEAD=off: Enable mail header patch
     LINKTHR=on: Link thread lib (for threaded extensions)
     ZTS=on: Force Zend Thread Safety (ZTS) build
===> Use 'make config' to modify these settings

Like mod_p55

**Comment by kelewind** [comment]
I have several production servers run on this mpm with php

**Comment by jperkin** [comment]
pkgsrc also supports it, but we aren't going to enable experimental options that are known to cause problems by default for all users, sorry.

You can either build it yourself with the option enabled, use the prefork mpm, or as I should have mentioned earlier you can use the event mpm with php-fpm.
