### ISSUE TITLE
2016Q1 mk.conf has syntax error

### ISSUE THREAD

**Issue by KrisShannon** [joyent/pkgbuild#5]
The final line in the new `mk.conf` to allow future upgrades is missing quotes around the `mk.conf.local` filename.

This causes bmake to die with:

`bmake: "/opt/local/etc/mk.conf" line 32: .include filename must be delimited by '"' or '<'`

**Comment by jperkin** [comment]
Oops, sorry.  This is now fixed, I've pushed rebuilt bootstrap kits and updated the checksums.  Thanks!
