### ISSUE TITLE
Allow `run-sandbox` to import your own GPG public key to `pkgsrc.gpg`

### ISSUE THREAD

**Issue by drscream** [joyent/pkgbuild#8]
If we would like to sign our own packages with your personal key we also need this key imported into the `/opt/local/etc/gnupg/pkgsrc.gpg` file. But this isn't possible because `run-sandbox` use the bootstrap files already exists in the pkgbuild-zone.

Would it be an idea to run the `gpg2` command in the `run-sandbox` script to import the key if it's provided with some variable? For example:

```
gpg2 --no-default-keyring --primary-keyring ${chrootdir}${PKGSRC_SYSCONFDIR}/gnupg/pkgsrc.gpg --recv ${PKGSRC_GPG_SIGN_AS}
```

**Comment by jperkin** [comment]
Which bit actually needs this? Verification should be turned off in sandboxes, i.e. https://github.com/joyent/pkgbuild/blob/master/scripts/run-sandbox#L71..L75

**Comment by drscream** [comment]
But I think if I build a package via `bmake package` the `pkg_info` is running and could not verify the signature if the key is not present.

```
=> Signing binary package /home/pbulk/build/misc/whohas/work/.packages/whohas-0.29nb6.tgz (GPG)
can't create `/root/.gnupg/random_seed': Read-only file system
===> Building binary package for whohas-0.29nb6
=> Creating binary package /data/packages/SmartOS/2016Q4/x86_64/All/whohas-0.29nb6.tgz
pkg_info: unable to verify signature: Signature key id 4c5fa701f7d8ac9b not found 
*** Error code 1
```

**Comment by jperkin** [comment]
Hmm, ok. I guess we should fix this by creating a temporary keyring and then updating `GPG_KEYRING_VERIFY` in `pkg_install.conf` to point to it. Could you verify this works and then I'll look at the best way to integrate it? Thanks.

**Comment by jperkin** [comment]
Actually I think just adding it to the sandbox keyring will be fine as per your initial suggestion, how about something like this?

```diff
diff --git a/scripts/run-sandbox b/scripts/run-sandbox
index 4beb8f19..80fe0853 100755
--- a/scripts/run-sandbox
+++ b/scripts/run-sandbox
@@ -84,6 +84,15 @@ if [ -n "${CMD_GPG}" -a -n "${PKGSRC_GPG_SIGN_AS}" ]; then
 		w
 		q
 	EOF
+	/usr/sbin/chroot ${chrootdir} /bin/bash -c "
+		${CMD_GPG} --no-default-keyring --primary-keyring \
+		    ${PKGSRC_SYSCONFDIR}/gnupg/pkgsrc.gpg ${PKGSRC_GPG_SIGN_AS} >/dev/null 2>&1
+		if [ \$? -ne 0 ]; then
+			echo 'Importing key ${PKGSRC_GPG_SIGN_AS} into ${PKGSRC_SYSCONFDIR}/gnupg/pkgsrc.gpg'
+			${CMD_GPG} --no-default-keyring --primary-keyring \
+			    ${PKGSRC_SYSCONFDIR}/gnupg/pkgsrc.gpg --recv ${PKGSRC_GPG_SIGN_AS} >/dev/null 2>&1
+		fi
+	"
 fi
 
 if [ ${USE_LOCAL_PKG_PATH} = yes ]; then
```

**Comment by jperkin** [comment]
Sorry, typo in that version, try this instead:

```diff
diff --git a/scripts/run-sandbox b/scripts/run-sandbox
index 4beb8f19..a82d45f6 100755
--- a/scripts/run-sandbox
+++ b/scripts/run-sandbox
@@ -84,6 +84,15 @@ if [ -n "${CMD_GPG}" -a -n "${PKGSRC_GPG_SIGN_AS}" ]; then
 		w
 		q
 	EOF
+	/usr/sbin/chroot ${chrootdir} /bin/bash -c "
+		${CMD_GPG} --no-default-keyring --primary-keyring \
+		    ${PKGSRC_SYSCONFDIR}/gnupg/pkgsrc.gpg --list-keys ${PKGSRC_GPG_SIGN_AS} >/dev/null 2>&1
+		if [ \$? -ne 0 ]; then
+			echo 'Importing key ${PKGSRC_GPG_SIGN_AS} into ${PKGSRC_SYSCONFDIR}/gnupg/pkgsrc.gpg'
+			${CMD_GPG} --no-default-keyring --primary-keyring \
+			    ${PKGSRC_SYSCONFDIR}/gnupg/pkgsrc.gpg --recv ${PKGSRC_GPG_SIGN_AS} >/dev/null 2>&1
+		fi
+	"
 fi
 
 if [ ${USE_LOCAL_PKG_PATH} = yes ]; then
```

**Comment by drscream** [comment]
It looks really good, I've tested the command manually and it's working for me.

**Comment by drscream** [comment]
Hello @jperkin, could I somehow support you to get the above patch from you merged into the master? If requested I could test it also on other systems if needed!

**Comment by jperkin** [comment]
Pushed, sorry for the delay.
